let mongoose=require("mongoose")
let express=require("express")
let cors=require("cors")
require("dotenv").config()
const rt = require("./routes/rt")
mongoose.connect("process.env.MONGO_URL").then(()=>{
    app.listen(process.env.port||5000)
})
let app=express()
app.listen(5000)
app.use(express.json())
app.use(express.urlencoded({"extended":true}))
app.use(cors())
app.use("/pimgs",express.static("./prodimgs"))
app.use("/",rt)
